### ISSUE TITLE
Navbar not responsive

### ISSUE THREAD

**Issue by schlich** [stldsa/site#15]
Mobile view breaks some containment and does not trigger top level flex-column/flex-row breakpoint

On mobile (sm breakpoint) we should have some nice vertically stacked menu items and the inline form/national dsa icon at the bottom

Menu template is in `stl_dsa/templates/menus` and base template is in `stl_dsa/templates`

Sass in `stl_dsa/static`

Feature branch at
https://github.com/stldsa/site/tree/layout

**Comment by yamanidev** [comment]
This is the smallest width viewport (320px), can you please elaborate more on this issue, because I don't seem to get it.

What looks off to me with the website on strain is the spacing between its sections, everything looks condensed.

Concerning the navbar, I think it would be much better if its elements were horizontally centered.


![smallest-viewport](https://user-images.githubusercontent.com/65856786/131220710-74ff5d2d-c22b-4957-9ccf-00b54a9b009d.png)

**Comment by schlich** [comment]
Hi yamani!  Thanks for joining the discussion.  The issue is in regards to the latest redesign, with changes that are committed in the repo and not deployed on the live site.  If you pull the latest commits and follow the def instructions you'll see what I mean!
